Admin model
xyield/xrpl-go pull request #31
Opened 2023-05-03 04:01 UTC by CreatureDev

2023-05-19 05:17 UTC, bmurphy333 commented on model/client/admin/key/wallet_propose_request.go
Is there a reason for missing out the rpc no key type request format? 
We will need to make sure we add check in for the seed when building the actual method

2023-05-19 05:41 UTC, bmurphy333 commented on model/client/admin/data/can_delete_request.go
should we have an omit empty on this struct? Since using with no param can be used to query the can_delete setting?

2023-05-19 06:26 UTC, bmurphy333 commented on model/client/admin/data/ledger_cleaner_request.go
Is this a websocket only method?

2023-05-19 07:34 UTC, bmurphy333 commented on model/client/admin/data/log_level_response.go
should this be just 'level' ?

2023-05-19 07:43 UTC, bmurphy333 commented on model/client/admin/server/stop_request.go
Is there a reason for no validation_seed model impl?

2023-05-19 07:52 UTC, bmurphy333 commented on model/client/admin/signing/sign_for_request.go
Any reason for not including offline, build_path, fee_mult_max, fee_div_max?

2023-05-19 07:58 UTC, bmurphy333 commented on model/client/admin/signing/sign_for_request.go
Method here should be "sign_for"

2023-05-19 08:23 UTC, bmurphy333 commented on model/client/admin/peer/peers_response.go
- Should tag and age in Cluster not have 'omitempty'? Although the example shows an empty cluster object but isn't marked as omitted in the docs lol... 
- Add 'protocol' to Peer struct. 
- Version should also be omitempty.

2023-05-19 08:23 UTC, bmurphy333 commented on model/client/admin/peer/peers_response.go
- Should tag and age in Cluster not have 'omitempty'? Although the example shows an empty cluster object but isn't marked as omitted in the docs lol... 
- Add 'protocol' to Peer struct. 
- Version should also be omitempty.

2023-05-19 08:30 UTC, bmurphy333 commented on model/client/admin/peer/peer_reservations_add_response.go
Why the use of pointers in the struct fields here? Is this because it might be omitted?

2023-05-19 15:49 UTC, CreatureDev commented on model/client/admin/server/stop_request.go
Validation seed is no longer supported, since rippled 0.29.1

2023-05-19 15:52 UTC, CreatureDev commented on model/client/admin/data/ledger_cleaner_request.go
by the documentation it is not clear
I believe the examples are just incomplete

2023-05-19 16:01 UTC, CreatureDev commented on model/client/admin/data/log_level_response.go
the documentation does say 'level' but the example shows as 'levels'
Looking at the rippled code `rippled/src/ripple/rpc/handlers/LogLevel.cpp` it appears that it is returned as 'levels

2023-05-19 16:04 UTC, CreatureDev commented on model/client/admin/key/wallet_propose_request.go
didn't notice there was a secondary format

2023-05-19 16:06 UTC, CreatureDev commented on model/client/admin/peer/peer_reservations_add_response.go
yes, omitempty doesn't work on structs but it does for pointers

2023-05-19 16:08 UTC, CreatureDev commented on model/client/admin/peer/peers_response.go
I believe the cluster list may be empty, but if a cluster is specified it will have at least a tag and age

2023-05-20 06:48 UTC, bmurphy333 commented on model/client/admin/status/consensus_info_response.go
lol so fun when the docs aren't the same as the example..

2023-05-28 03:07 UTC, bmurphy333 commented on model/client/admin/status/feature_response.go
name should be omitempty

2023-08-09 23:53 UTC, bmurphy333 requested changes

2023-08-09 23:53 UTC, bmurphy333 commented on model/client/admin/status/validator_info_response.go
is there a reason for no test for this?

2023-08-09 23:53 UTC, bmurphy333 commented on model/client/admin/status/get_counts_test.go
How come there is no model for print method? I guess there are no outlines for what's in the response otehr than just being the standard map interface? The docs are kinda confusing tho for whether it just websocket/command line. I guess if it is just either than ok to miss it out for now

2023-08-09 23:53 UTC, bmurphy333 commented on model/client/admin/data/can_delete_request.go
Do you think no omit empty?

2023-08-10 11:06 UTC, CreatureDev commented on model/client/admin/status/get_counts_test.go
I was not certain it was valid for websocket/rpc since there was no example response

2023-08-10 23:02 UTC, bmurphy333 commented on model/client/admin/status/get_counts_test.go
Ah ok no probs. Just had a look and java lib doesn't have this method. They don't have any websocket impl tho. Can just leave it out for now

2023-08-10 23:02 UTC, bmurphy333 approved these changes

2023-08-10 23:15 UTC, merged